name: Build / Publish

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - linux-x64
          - linux-arm64
          - osx-x64
          - osx-arm64
          - win-x64
          - win-x86
          - win-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Git SHA Versioning
        run: |
          SHORT_SHA=$(echo ${GITHUB_SHA::7})
          echo SHORT_SHA=$SHORT_SHA >> $GITHUB_ENV
          echo DIST_NAME=itmserv-git-$SHORT_SHA-${{ matrix.arch }} > $GITHUB_ENV
          sed -i 's/public static string Version = "\(.*\)";/public static string Version = "\1 (git-${{ github.sha }})";/' Program.cs
          cat  Program.cs | grep Version
      - name: .NET Restore
        run:  dotnet restore -r ${{ matrix.arch }}
      - name: .NET Build & Publish
        run:  dotnet publish -c Release -p:PblishSingleFile=true -p:DebugType=None -p:DebugSymbols=false --self-contained true -r ${{ matrix.arch }}
      - name: Archive
        run: |
          mv bin/Release/net8.0/${{ matrix.arch }}/publish/ ${DIST_NAME}
          cp  -r IPA ${DIST_NAME}
          zip -r ${DIST_NAME}.zip ${DIST_NAME}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DIST_NAME }}
          path: ${{ env.DIST_NAME }}.zip
  
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*.zip
